### ISSUE TITLE
Conflicts with other plugins

### ISSUE THREAD

**Issue by ebofi** [techaffinity/freshchat-phonegap#1]
Hi,

When we use this plugin via phonegap 
        	<gap:plugin spec="https://github.com/techaffinity/freshchat-phonegap.git" source="git" />
We have the APK generation failed with log 

Installing "cordova-plugin-buildinfo" at "1.1.0" for android
Fetching plugin "cordova-plugin-googleplus" via npm
Installing "cordova-plugin-googleplus" at "5.2.1" for android
Subproject Path: CordovaLib
"plugman-151 install --platform android --project  --plugin cordova-plugin-camera@2.4.1 --nohooks=.": Fetching plugin "cordova-plugin-camera@2.4.1" via npm
Installing "cordova-plugin-camera" at "2.4.1" for android
Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
Dependent plugin "cordova-plugin-compat" already installed on android.
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-camera': CordovaError: Uh oh!
"/res/xml/provider_paths.xml" already exists!
    at copyNewFile (/cordova/lib/pluginHandlers.js:248:15)
    at install (/cordova/lib/pluginHandlers.js:43:17)
    at Object.process (/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at /cordova/Api.js:254:18
    at _fulfilled (/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/cordova/node_modules/q/q.js:816:13)
    at /cordova/node_modules/q/q.js:570:49
Uh oh!
"/res/xml/provider_paths.xml" already exists!

**Comment by ebofi** [comment]
Using shallow clone
Repository "https://github.com/techaffinity/freshchat-phonegap.git" checked out to git ref "master" at "ab2d1f4".
Installing "cordova-plugin-freshchat" at "1.1.0" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-freshchat': CordovaError: Uh oh!
"/res/xml/provider_paths.xml" already exists!
    at copyNewFile (/cordova/lib/pluginHandlers.js:248:15)
    at install (/cordova/lib/pluginHandlers.js:43:17)
    at Object.process (/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at /cordova/Api.js:254:18
    at _fulfilled (/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/cordova/node_modules/q/q.js:816:13)
    at /cordova/node_modules/q/q.js:570:49
Uh oh!
"/res/xml/provider_paths.xml" already exists!

**Comment by techaffinity** [comment]
@ebofi We have resolved the conflict issues while merging with other plugins. Please check on the latest commit changes.

**Comment by ebofi** [comment]
Thanks.. Checking

**Comment by wishbooks** [comment]
when i try to add the plugin from the command specified in steps it showed this error

Jays-MacBook-Pro:hello jay$ sudo cordova plugin add https://github.com/techaffinity/freshchat-phonegap.git
(node:6762) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/techaffinity/freshchat-phonegap.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/techaffinity/freshchat-phonegap.git /Users/jay/.npm/_cacache/tmp/git-clone-045cb2e1
npm ERR! /Users/jay/.npm/_cacache/tmp/git-clone-045cb2e1/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/jay/.npm/_logs/2018-07-06T07_07_33_337Z-debug.log
at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)
(node:6762) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6762) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

so i added the plugin locally
