### ISSUE TITLE
Click in FAQ resulting force close error

### ISSUE THREAD

**Issue by jefsteward** [techaffinity/freshchat-phonegap#2]
Hi @techaffinity ,
FAQ is not working in this awesome freshchat-phonegap. I tried with native one and it's okay. 
Can you please check it? I give you two image comparison (phonegap vs native) below. Thank you.

Phonegap
![phoengap_faq](https://user-images.githubusercontent.com/19892852/34926782-58df2698-f9e4-11e7-8ad2-1be46480549a.jpeg)
![phonegap_error](https://user-images.githubusercontent.com/19892852/34926786-5d99fc08-f9e4-11e7-91e9-47b1b9018a5c.jpeg)

Native
![native_faq](https://user-images.githubusercontent.com/19892852/34926800-73ccb254-f9e4-11e7-9896-0da337ed65b8.jpeg)
![native_faq_okay](https://user-images.githubusercontent.com/19892852/34926802-7602f146-f9e4-11e7-9fc2-ca95aedf9071.jpeg)

**Comment by techaffinity** [comment]
Hi @jefsteward , can you share me error log from android studio.

**Comment by jefsteward** [comment]
Hi @techaffinity 
I build it using command line, so I don't know how to get error log from android studio. Can you tell me how?
This is what I get from adb logcat

01-18 16:15:07.007   780   790 I ActivityManager: START u0 {cmp=id.compro.newcomprosupport/com.freshchat.consumer.sdk.activity.ArticleListActivity (has extras)} from uid 10564 on display 0
01-18 16:15:07.018   204   816 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
01-18 16:15:07.038   204   816 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
01-18 16:15:07.038   204   816 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
01-18 16:15:07.038   204   816 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
01-18 16:15:07.039   204   816 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
01-18 16:15:07.040  1226  1226 W Binder_4: type=1400 audit(0.0:146471): avc: denied { ioctl } for path="socket:[5148125]" dev="sockfs" ino=5148125 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
01-18 16:15:07.040  1226  1226 W Binder_4: type=1400 audit(0.0:146472): avc: denied { ioctl } for path="socket:[5148125]" dev="sockfs" ino=5148125 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
01-18 16:15:07.086 16347 16579 I FRESHCHAT_SERVICE: Now Processing f
01-18 16:15:07.108 16347 16347 D AndroidRuntime: Shutting down VM
01-18 16:15:07.109 16347 16347 E AndroidRuntime: FATAL EXCEPTION: main
01-18 16:15:07.109 16347 16347 E AndroidRuntime: Process: id.compro.newcomprosupport, PID: 16347
01-18 16:15:07.109 16347 16347 E AndroidRuntime: java.lang.UnsupportedOperationException: This is not supported, use MenuItemCompat.setOnActionExpandListener()
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v7.view.menu.MenuItemImpl.setOnActionExpandListener(MenuItemImpl.java:740)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v4.view.MenuItemCompat.setOnActionExpandListener(MenuItemCompat.java:363)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at com.freshchat.consumer.sdk.activity.ArticleListActivity.onCreateOptionsMenu(Unknown Source)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:2852)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:320)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:258)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1320)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1600)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:92)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:131)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-18 16:15:07.109 16347 16347 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-18 16:15:07.110   780  1796 W ActivityManager:   Force finishing activity id.compro.newcomprosupport/com.freshchat.consumer.sdk.activity.ArticleListActivity
01-18 16:15:07.113   780  1796 W ActivityManager:   Force finishing activity id.compro.newcomprosupport/com.freshchat.consumer.sdk.activity.CategoryListActivity
01-18 16:15:07.118   780 16580 W DropBoxManagerService: Dropping: data_app_crash (1774 > 0 bytes)
01-18 16:15:07.151   780 28931 I OpenGLRenderer: Initialized EGL, version 1.4
01-18 16:15:07.613   780   794 W ActivityManager: Activity pause timeout for ActivityRecord{580aa2e u0 id.compro.newcomprosupport/com.freshchat.consumer.sdk.activity.ArticleListActivity t2408 f}
01-18 16:15:10.236   204   816 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
01-18 16:15:10.237   204   816 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
01-18 16:15:17.011   780   794 W ActivityManager: Launch timeout has expired, giving up wake lock!
01-18 16:15:17.119   780   794 W ActivityManager: Activity destroy timeout for ActivityRecord{53687ef u0 id.compro.newcomprosupport/com.freshchat.consumer.sdk.activity.CategoryListActivity t2408 f}

**Comment by ebofi** [comment]
@jefsteward @techaffinity 
I had also faced similar issue on the Previous Hotline Plugin, when the customer clicks on the FAQ the app got crashed.

**Comment by jefsteward** [comment]
@ebofi 
So in current version still crashed?

**Comment by ebofi** [comment]
@jefsteward  So currently i am not using the FAQ in the app.  The answer i had got from the Freshdesk for this was their plugin conflicts with Google Support plugin etc.


The Exact reply was this 👍 

Hi Stanly, 
Hotline SDK uses appcompat-v7 for ensuring compatibility with various versions of Android.

Appcompat-v7 is a library provided by Google and itself has a dependency on support-v4. A specific version of appcompat-v7 is compatible with only specific/same version of support-v4. Hotline SDK doesn't have control over versions of the appcompat-v7/support-v4 being included in the app integrating the Hotline SDK.

Your app is including incompatible versions support-v4 and appcompat-v7. This will have to be fixed in your app. Please make sure this is fixed. 

Thanks,
Sudhir

**Comment by jefsteward** [comment]
@techaffinity @shagulameedn   any updates on this? Pretty sure @ebofi answer could give a clue

**Comment by ebofi** [comment]
@techaffinity @shagulameedn @jefsteward  any update on this

**Comment by jefsteward** [comment]
@ebofi no updates. Let's hope they fix this.

**Comment by jasonandress** [comment]
I've fixed this same issue before with the old Hotline version. The problem then was another plugin I use cordova-plugin-local-notifications. That plugin didn't lock the support-v4 and Android released a beta version which caused the issues. I've tried to find another plugin that is doing the same thing with no luck so far.

-        <framework src="com.android.support:support-v4:+" value="gradle" />
+        <framework src="com.android.support:support-v4:25.+" value="gradle" />

I have to now probably go back through each support v4 release and figure out which one it was using the last time it works.

I'm also going to see how to implement the web version in my app. I don't see why we need a native android/ios version when the web one may work. If I get it working I'll update the post.

**Comment by jasonandress** [comment]
I've fixed it for my app. The issue for me was in the phonegap-plugin. I've forked the techaffinity/phonegap-plugin-push and modified the plugin.xml

If you want you can use my fork. I'm not merging it as I'm not sure how this will work with everyone's app as we all use different plugins with different issues.  I'm sure someone could make these changes, but that's up to @techaffinity 

https://github.com/jasonandress/phonegap-plugin-push-1

I've added com.android.support:appcompat-v7 and locked it to 26.
I've also locked com.android.support:support-v4 to 26 as well.

<framework src="com.android.support:support-v4:26+"/>
<framework src="com.android.support:appcompat-v7:26+"/>

**Comment by techaffinity** [comment]
Hi Jason
Thanks a lot for the suggestion, we will sure look into it and check if this fix is compatible for other versions and scenarios, then will update the git. Thanks again

**Comment by marceloaraujo** [comment]
Hello guys.
I'm sorry but I've been facing the same issue.
I'm trying to add the @jasonandress fork in my project using the following command:
`ionic cordova plugin add https://github.com/jasonandress/phonegap-plugin-push-1.git`, but the console returns me the following error:

`UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/jasonandress/phonegap-plugin-push-1.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.`

Can anyone help me on this case?
Thanks.

**Comment by jasonandress** [comment]
Hey there. Let me check that out later this afternoon. I may have to refresh the latest changes to the parent repo just committed Into my fork. There's an issue with the Freshchat sdk version 1.5.3 which they fixed this morning.

**Comment by marceloaraujo** [comment]
Hello @jasonandress 
Ok, I'll wait. When I solve this issue, I'll let you know.
Thanks for helping me.

**Comment by jasonandress** [comment]
@marceloaraujo I've merged the latest changes from techaffinity's repo into mine. Give it a try.
