### ISSUE TITLE
Build Failing on Both Android and IOS

### ISSUE THREAD

**Issue by ebofi** [techaffinity/freshchat-phonegap#8]
Hi TechAffinity,

We see that you people are not interested to maintain this project and we dont know what is the reason for making this git. If you are not interested to maintain this for a product like Fresh-works. We request you people to intimate fresh works that you are closing this branch. 

We had reported a bug on 
https://github.com/techaffinity/freshchat-phonegap/issues/2 But No Reply on that, and today we see that again the plugin is making the build fail. So please do something to fix the issue

"plugman-151 install --platform android --project  --plugin https://github.com/techaffinity/freshchat-phonegap.git --nohooks=.": Fetching plugin "https://github.com/techaffinity/freshchat-phonegap.git" via git clone
Using shallow clone
Repository "https://github.com/techaffinity/freshchat-phonegap.git" checked out to git ref "master" at "7fe68a4".
Installing "cordova-plugin-freshchat" at "1.2.0" for android
Failed to install 'cordova-plugin-freshchat': Error: ENOENT: no such file or directory, open '/AndroidManifest.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.parseElementtreeSync (/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/cordova/Api.js:223:57)
    at handleInstall (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:364:24
    at _fulfilled (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:787:54)
ENOENT: no such file or directory, open '/AndroidManifest.xml'

**Comment by techaffinity** [comment]
We are not getting any feedback and we are closing this issue.
